name: arbil_royal_app
description: تطبيق أربيل رويال للعقارات
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  url_launcher: ^6.2.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false  # هذا هو السطر الذي يحل المشكلة، يخبر الأداة ألا تبحث عن أي شيء يخص أبل
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  assets:
    - assets/images/
