name: seachat
description: SeaChat Real Estate App - تطبيق عقارات أربيل
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # الباك اند والشبكة
  supabase_flutter: ^2.8.0
  connectivity_plus: ^6.0.5
  url_launcher: ^6.3.1
  
  # الواجهة والتصميم
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  
  # الخرائط والموقع
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  
  # الوسائط
  image_picker: ^1.1.2
  
  # أدوات مساعدة
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    assets/images/splash_bg.png
    assets/images/app_icon.png
