name: Build Flutter APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Force Clean and Build
        run: |
          # مسح أي ملفات أندرويد قديمة قد تكون مسببة للمشاكل
          rm -rf android/
          
          # إجبار فلاتر على إعادة إنشاء ملفات الأندرويد من الصفر
          flutter create .
          
          # تثبيت المكتبات
          flutter pub get
          
          # البناء النهائي
          flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
